[package]
name = "benchmarks"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
tempfile = "3.3.0"
okaywal = { path = "../" }
timings = { path = "../../timings" }
bytesize = "1.1.0"
sharded-log = { version = "0.0.1", optional = true }

[[bench]]
name = "benchmarks"
harness = false
