name: Benchmarks

on: [push]

jobs:
  benchmark:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Rust
        uses: hecrj/setup-rust-action@v1

      - name: Build benchmarks
        run: |
          cargo bench --no-run

      - name: Run benchmarks
        run: |
          cargo bench
