name: Docs

on: [push]

jobs:
  docs:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Install Rust
        uses: hecrj/setup-rust-action@v1

      - uses: actions/checkout@v2
      - name: Generate Docs
        run: |
          cargo doc --no-deps --all-features

      - name: Deploy Docs
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          branch: gh-pages
          folder: target/doc/
          git-config-name: kl-botsu
          git-config-email: botsu@khonsulabs.com
          target-folder: /main/
          clean: true
